"""Build an English greeting from the same Playwrite VN Light font as 'xin chào'.

The source is the Google Fonts 1.003 subset of the letters in 'Hello'.
The finished SVG is inlined at runtime so the existing preloader can control
its pen animation without a flash or a separate network request.

SUPERSEDED (2026-09-28): the animation is now built by tools/hello-pen (see its README);
this script only documents how the outlines were shaped and stops unless --force is given.
"""
import sys
if '--force' not in sys.argv:
    raise SystemExit('superseded by tools/hello-pen (see tools/hello-pen/README.md); pass --force to run anyway')
from pathlib import Path
import json
import os
import re
import uharfbuzz as hb
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / 'assets/lettering/playwrite-vn-300-Hello.ttf'
FONT_BYTES = FONT.read_bytes()
FONT_DATA = TTFont(FONT)
GLYPHS = FONT_DATA.getGlyphSet()
TEXT = 'Hello'
SCALE = .118
BASELINE = 160

buffer = hb.Buffer()
buffer.add_str(TEXT)
buffer.guess_segment_properties()
hb.shape(hb.Font(hb.Face(FONT_BYTES)), buffer)
left = (640 - sum(p.x_advance for p in buffer.glyph_positions) * SCALE) / 2
x = left
groups = {i: [] for i in range(len(TEXT))}
for info, pos in zip(buffer.glyph_infos, buffer.glyph_positions):
    glyph = GLYPHS[FONT_DATA.getGlyphOrder()[info.codepoint]]
    transform = (SCALE, 0, 0, -SCALE,
                 x + pos.x_offset * SCALE, BASELINE - pos.y_offset * SCALE)
    pen = SVGPathPen(GLYPHS)
    glyph.draw(TransformPen(pen, transform))
    path = re.sub(r'-?\d+\.\d+', lambda m: f'{float(m[0]):.3f}'.rstrip('0').rstrip('.'), pen.getCommands())
    bounds = BoundsPen(GLYPHS)
    glyph.draw(TransformPen(bounds, transform))
    groups[info.cluster].append((path, bounds.bounds))
    x += pos.x_advance * SCALE

# The paths follow the centre of each actual glyph stroke. The masks only
# reveal original font outlines; they never substitute a different lettering.
STROKES = [
    (0, 'H-left', 'M149 33 C158 12 179 7 187 25 C190 34 188 49 188 67 L188 131 C188 150 180 160 170 158 C156 155 160 134 173 121 C188 105 226 92 252 78', 80, 474),
    (0, 'H-right', 'M267 14 C254 9 251 25 251 45 L251 130 C251 153 265 161 282 156 C294 152 301 143 307 132', 570, 296),
    (0, 'H-loop', 'M267 14 C281 8 285 23 285 38 C283 72 270 109 252 128', 570, 296),
    (1, 'e', 'M306 129 C317 127 326 119 326 110 C326 102 316 100 309 105 C298 113 293 131 300 145 C306 158 318 161 331 156 C344 151 351 138 358 128', 882, 318),
    (1, 'e-to-l-loop', 'M367 13 C379 9 380 22 380 38 C379 71 371 107 357 129', 1216, 252),
    (2, 'l-one', 'M367 13 C357 11 356 27 356 44 L356 130 C356 153 368 161 383 156 C391 153 399 145 403 134', 1216, 252),
    (2, 'l-one-loop', 'M367 13 C379 9 380 22 380 38 C379 71 371 107 357 129', 1216, 252),
    (2, 'l-one-to-two-loop', 'M413 13 C425 9 427 22 427 38 C426 71 418 107 403 129', 1484, 252),
    (3, 'l-two', 'M413 13 C403 11 402 27 402 44 L402 130 C402 153 414 161 429 156 C436 153 442 147 445 139', 1484, 252),
    (3, 'l-two-loop', 'M413 13 C425 9 427 22 427 38 C426 71 418 107 403 129', 1484, 252),
    (4, 'o', 'M467 102 C452 102 444 113 444 130 C444 147 452 159 467 159 C482 159 491 147 491 131 C491 114 482 102 467 102 Z', 1752, 244),
]

defs = []
ink = []
for i, group in groups.items():
    pens = []
    for _, name, guide, delay, duration in (s for s in STROKES if s[0] == i):
        pens.append(f'<path class="hello__pen" data-stroke="{name}" pathLength="1" d="{guide}" style="--delay:{delay}ms;--duration:{duration}ms;stroke-width:36"/>')
    defs.append(f'<mask id="hello-en-mask-{i}" maskUnits="userSpaceOnUse" x="0" y="-20" width="640" height="240" style="mask-type:luminance">' + ''.join(pens) + '</mask>')
    ink.append(f'<g mask="url(#hello-en-mask-{i})">' + ''.join(f'<path d="{p}"/>' for p, _ in group) + '</g>')

svg = ('<svg class="hello hello--en" viewBox="0 -20 640 220" data-duration="1298" '
       'role="img" aria-label="Hello" focusable="false">'
       '<defs>' + ''.join(defs) + '</defs>'
       '<g class="hello__ink">' + ''.join(ink) + '</g></svg>')
(ROOT / 'js/hello-en.js').write_text('/* Exact Playwrite VN 300 outlines for the English preloader. Generated by tools/build-hello-en.py. */\nwindow.LTV_HELLO_EN = ' + json.dumps(svg, ensure_ascii=False) + ';\n', encoding='utf-8')

preview = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -20 640 220">'
           '<rect x="0" y="-20" width="640" height="220" fill="#122039"/>'
           '<g fill="white">' + ''.join(f'<path d="{p}"/>' for group in groups.values() for p, _ in group) + '</g></svg>')
(Path(os.environ['TEMP']) / 'ltv-hello-en-preview.svg').write_text(preview, encoding='utf-8')
print('Generated Playwrite VN English greeting: Hello')
